@APIGateway_HostAddress = http://localhost:8080

GET {{APIGateway_HostAddress}}/api/invoices/
Accept: application/json

###

GET {{APIGateway_HostAddress}}/uuid
Accept: application/json

###

POST {{APIGateway_HostAddress}}/api/invoices HTTP/1.1
content-type: application/json

{
    "id": "08dd682b-d5f4-3f5b-f278-318b01000000",
    "to": "me",
    "amount": "1337.90",
    "details": "do great things",
    "invoiceDate": "2025-12-20"
}