apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: apigateway:latest  # Build this locally first
        imagePullPolicy: Never  # Use local image only
        ports:
        - containerPort: 8080
        env:
        - name: Jaeger__Host
          value: "http://jaeger:4317"