apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite:latest
        args: ["azurite-blob", "--blobHost", "0.0.0.0", "--loose"]
        ports:
        - containerPort: 10000