apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: masstransit/rabbitmq:latest
        ports:
        - containerPort: 5672  # AMQP
        - containerPort: 15672  # Management UI