apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/jaeger:2.4.0
        ports:
        - containerPort: 6831
        - containerPort: 16686
        - containerPort: 4317
        - containerPort: 14250
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: agent
    protocol: UDP
    port: 6831
    targetPort: 6831
  - name: ui
    protocol: TCP
    port: 16686
    targetPort: 16686
  - name: otlp-grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: grpc
    protocol: TCP
    port: 14250
    targetPort: 14250
  type: LoadBalancer