apiVersion: apps/v1
kind: Deployment
metadata:
  name: persister
  labels:
    app: persister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persister
  template:
    metadata:
      labels:
        app: persister
    spec:
      containers:
      - name: persister
        image: persister:latest  # Build this locally first
        imagePullPolicy: Never  # Use local image only
        env:
        - name: Jaeger__Host
          value: "http://jaeger:4317"